<h3>TimeDistributed Layer</h3>

LSTMs are powerful, but hard to use and hard to configure, especially for beginners.
An added complication is the TimeDistributed Layer (and the former TimeDistributedDense layer) that is cryptically described as a layer wrapper

   <font color="red"> This wrapper allows us to apply a layer to every temporal slice of an input </font>

How and when are you supposed to use this wrapper with LSTMs?

The confusion is compounded when you search through discussions about the wrapper layer on the Keras GitHub issues and StackOverflow.

For example, in the issue “When and How to use TimeDistributedDense,” fchollet (Keras’ author) explains:

   <font color="red"> TimeDistributedDense applies a same Dense (fully-connected) operation to every timestep of a 3D tensor.</font>

This makes perfect sense if you already understand what the TimeDistributed layer is for and when to use it, but is no help at all to a beginner.

This tutorial aims to clear up confusion around using the TimeDistributed wrapper with LSTMs with worked examples that you can inspect, run, and play with to help your concrete understanding.

In [1]:
from numpy import array
length = 5
seq = array([i/float(length) for i in range(length)])
print(seq)

[0.  0.2 0.4 0.6 0.8]


In [15]:
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import TimeDistributed

# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(len(seq), 1, 1)
y = seq.reshape(len(seq), 1)

In [ ]:
# define LSTM configuration
n_neurons = length
n_batch = length
n_epoch = 1000

In [7]:
X, X.shape

(array([[[0. ]],
 
        [[0.2]],
 
        [[0.4]],
 
        [[0.6]],
 
        [[0.8]]]), (5, 1, 1))

In [8]:
y, y.shape

(array([[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]), (5, 1))

Many to one architecture

In [2]:
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(1, 1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=2)

# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result:
    print('%.1f' % value)

Using TensorFlow backend.


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/1000
 - 1s - loss: 0.2512
Epoch 2/1000
 - 0s - loss: 0.2490
Epoch 3/1000
 - 0s - loss: 0.2471
Epoch 4/1000
 - 0s - loss: 0.2450
Epoch 5/1000
 - 0s - loss: 0.2428
Epoch 6/1000
 - 0s - loss: 0.2407
Epoch 7/1000
 - 0s - loss: 0.2385
Epoch 8/1000
 - 0s - loss: 0.2364
Epoch 9/1000
 - 0s - loss: 0.2344
Epoch 10/1000
 - 0s - loss: 0.2323
Epoch 11/1000
 - 0s - loss: 0.2302
Epoch 12/1000
 - 0s - loss: 0.2281
Epoch 13/1000
 - 0s - loss: 0.2261
Epoch 14/1000
 - 0s - loss: 0.2240
Epoch 15/1000
 - 0s - loss: 0.2220
Epoch 16/1000
 - 0s

Epoch 215/1000
 - 0s - loss: 0.0454
Epoch 216/1000
 - 0s - loss: 0.0452
Epoch 217/1000
 - 0s - loss: 0.0450
Epoch 218/1000
 - 0s - loss: 0.0449
Epoch 219/1000
 - 0s - loss: 0.0447
Epoch 220/1000
 - 0s - loss: 0.0445
Epoch 221/1000
 - 0s - loss: 0.0444
Epoch 222/1000
 - 0s - loss: 0.0442
Epoch 223/1000
 - 0s - loss: 0.0440
Epoch 224/1000
 - 0s - loss: 0.0439
Epoch 225/1000
 - 0s - loss: 0.0437
Epoch 226/1000
 - 0s - loss: 0.0436
Epoch 227/1000
 - 0s - loss: 0.0434
Epoch 228/1000
 - 0s - loss: 0.0433
Epoch 229/1000
 - 0s - loss: 0.0431
Epoch 230/1000
 - 0s - loss: 0.0430
Epoch 231/1000
 - 0s - loss: 0.0428
Epoch 232/1000
 - 0s - loss: 0.0427
Epoch 233/1000
 - 0s - loss: 0.0425
Epoch 234/1000
 - 0s - loss: 0.0424
Epoch 235/1000
 - 0s - loss: 0.0423
Epoch 236/1000
 - 0s - loss: 0.0421
Epoch 237/1000
 - 0s - loss: 0.0420
Epoch 238/1000
 - 0s - loss: 0.0418
Epoch 239/1000
 - 0s - loss: 0.0417
Epoch 240/1000
 - 0s - loss: 0.0416
Epoch 241/1000
 - 0s - loss: 0.0414
Epoch 242/1000
 - 0s - loss:

Epoch 443/1000
 - 0s - loss: 0.0209
Epoch 444/1000
 - 0s - loss: 0.0208
Epoch 445/1000
 - 0s - loss: 0.0207
Epoch 446/1000
 - 0s - loss: 0.0206
Epoch 447/1000
 - 0s - loss: 0.0205
Epoch 448/1000
 - 0s - loss: 0.0204
Epoch 449/1000
 - 0s - loss: 0.0203
Epoch 450/1000
 - 0s - loss: 0.0202
Epoch 451/1000
 - 0s - loss: 0.0201
Epoch 452/1000
 - 0s - loss: 0.0200
Epoch 453/1000
 - 0s - loss: 0.0199
Epoch 454/1000
 - 0s - loss: 0.0198
Epoch 455/1000
 - 0s - loss: 0.0197
Epoch 456/1000
 - 0s - loss: 0.0197
Epoch 457/1000
 - 0s - loss: 0.0196
Epoch 458/1000
 - 0s - loss: 0.0195
Epoch 459/1000
 - 0s - loss: 0.0194
Epoch 460/1000
 - 0s - loss: 0.0193
Epoch 461/1000
 - 0s - loss: 0.0192
Epoch 462/1000
 - 0s - loss: 0.0191
Epoch 463/1000
 - 0s - loss: 0.0190
Epoch 464/1000
 - 0s - loss: 0.0189
Epoch 465/1000
 - 0s - loss: 0.0188
Epoch 466/1000
 - 0s - loss: 0.0187
Epoch 467/1000
 - 0s - loss: 0.0187
Epoch 468/1000
 - 0s - loss: 0.0186
Epoch 469/1000
 - 0s - loss: 0.0185
Epoch 470/1000
 - 0s - loss:

Epoch 671/1000
 - 0s - loss: 0.0047
Epoch 672/1000
 - 0s - loss: 0.0046
Epoch 673/1000
 - 0s - loss: 0.0046
Epoch 674/1000
 - 0s - loss: 0.0045
Epoch 675/1000
 - 0s - loss: 0.0045
Epoch 676/1000
 - 0s - loss: 0.0044
Epoch 677/1000
 - 0s - loss: 0.0044
Epoch 678/1000
 - 0s - loss: 0.0044
Epoch 679/1000
 - 0s - loss: 0.0043
Epoch 680/1000
 - 0s - loss: 0.0043
Epoch 681/1000
 - 0s - loss: 0.0042
Epoch 682/1000
 - 0s - loss: 0.0042
Epoch 683/1000
 - 0s - loss: 0.0042
Epoch 684/1000
 - 0s - loss: 0.0041
Epoch 685/1000
 - 0s - loss: 0.0041
Epoch 686/1000
 - 0s - loss: 0.0041
Epoch 687/1000
 - 0s - loss: 0.0040
Epoch 688/1000
 - 0s - loss: 0.0040
Epoch 689/1000
 - 0s - loss: 0.0039
Epoch 690/1000
 - 0s - loss: 0.0039
Epoch 691/1000
 - 0s - loss: 0.0039
Epoch 692/1000
 - 0s - loss: 0.0038
Epoch 693/1000
 - 0s - loss: 0.0038
Epoch 694/1000
 - 0s - loss: 0.0038
Epoch 695/1000
 - 0s - loss: 0.0037
Epoch 696/1000
 - 0s - loss: 0.0037
Epoch 697/1000
 - 0s - loss: 0.0037
Epoch 698/1000
 - 0s - loss:

 - 0s - loss: 3.7214e-04
Epoch 891/1000
 - 0s - loss: 3.6717e-04
Epoch 892/1000
 - 0s - loss: 3.6227e-04
Epoch 893/1000
 - 0s - loss: 3.5743e-04
Epoch 894/1000
 - 0s - loss: 3.5266e-04
Epoch 895/1000
 - 0s - loss: 3.4794e-04
Epoch 896/1000
 - 0s - loss: 3.4329e-04
Epoch 897/1000
 - 0s - loss: 3.3870e-04
Epoch 898/1000
 - 0s - loss: 3.3417e-04
Epoch 899/1000
 - 0s - loss: 3.2970e-04
Epoch 900/1000
 - 0s - loss: 3.2528e-04
Epoch 901/1000
 - 0s - loss: 3.2093e-04
Epoch 902/1000
 - 0s - loss: 3.1663e-04
Epoch 903/1000
 - 0s - loss: 3.1239e-04
Epoch 904/1000
 - 0s - loss: 3.0821e-04
Epoch 905/1000
 - 0s - loss: 3.0408e-04
Epoch 906/1000
 - 0s - loss: 3.0001e-04
Epoch 907/1000
 - 0s - loss: 2.9599e-04
Epoch 908/1000
 - 0s - loss: 2.9203e-04
Epoch 909/1000
 - 0s - loss: 2.8812e-04
Epoch 910/1000
 - 0s - loss: 2.8426e-04
Epoch 911/1000
 - 0s - loss: 2.8046e-04
Epoch 912/1000
 - 0s - loss: 2.7670e-04
Epoch 913/1000
 - 0s - loss: 2.7300e-04
Epoch 914/1000
 - 0s - loss: 2.6935e-04
Epoch 915/1000


Many to Many architecture

In [11]:
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length)

In [12]:
# create LSTM
model = Sequential()
model.add(LSTM(5, input_shape=(5, 1)))
model.add(Dense(length))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())
model.fit(X, y, epochs=500, batch_size=1, verbose=2)

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 5)                 140       
_________________________________________________________________
dense_3 (Dense)              (None, 5)                 30        
Total params: 170
Trainable params: 170
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/500
 - 1s - loss: 0.2208
Epoch 2/500
 - 0s - loss: 0.2194
Epoch 3/500
 - 0s - loss: 0.2176
Epoch 4/500
 - 0s - loss: 0.2157
Epoch 5/500
 - 0s - loss: 0.2139
Epoch 6/500
 - 0s - loss: 0.2122
Epoch 7/500
 - 0s - loss: 0.2103
Epoch 8/500
 - 0s - loss: 0.2085
Epoch 9/500
 - 0s - loss: 0.2067
Epoch 10/500
 - 0s - loss: 0.2049
Epoch 11/500
 - 0s - loss: 0.2031
Epoch 12/500
 - 0s - loss: 0.2013
Epoch 13/500
 - 0s - loss: 0.1995
Epoch 14/500
 - 0s - loss: 0.1977
Epoch 15/500
 - 0s - loss: 0.1960
Epoch 16/500
 - 0s - loss: 0.1942


Epoch 217/500
 - 0s - loss: 1.5287e-04
Epoch 218/500
 - 0s - loss: 1.4465e-04
Epoch 219/500
 - 0s - loss: 1.3685e-04
Epoch 220/500
 - 0s - loss: 1.2944e-04
Epoch 221/500
 - 0s - loss: 1.2240e-04
Epoch 222/500
 - 0s - loss: 1.1572e-04
Epoch 223/500
 - 0s - loss: 1.0938e-04
Epoch 224/500
 - 0s - loss: 1.0337e-04
Epoch 225/500
 - 0s - loss: 9.7660e-05
Epoch 226/500
 - 0s - loss: 9.2246e-05
Epoch 227/500
 - 0s - loss: 8.7113e-05
Epoch 228/500
 - 0s - loss: 8.2247e-05
Epoch 229/500
 - 0s - loss: 7.7634e-05
Epoch 230/500
 - 0s - loss: 7.3263e-05
Epoch 231/500
 - 0s - loss: 6.9123e-05
Epoch 232/500
 - 0s - loss: 6.5200e-05
Epoch 233/500
 - 0s - loss: 6.1486e-05
Epoch 234/500
 - 0s - loss: 5.7970e-05
Epoch 235/500
 - 0s - loss: 5.4642e-05
Epoch 236/500
 - 0s - loss: 5.1493e-05
Epoch 237/500
 - 0s - loss: 4.8514e-05
Epoch 238/500
 - 0s - loss: 4.5696e-05
Epoch 239/500
 - 0s - loss: 4.3032e-05
Epoch 240/500
 - 0s - loss: 4.0514e-05
Epoch 241/500
 - 0s - loss: 3.8135e-05
Epoch 242/500
 - 0s - los

 - 0s - loss: 8.2730e-13
Epoch 428/500
 - 0s - loss: 6.9478e-13
Epoch 429/500
 - 0s - loss: 5.5533e-13
Epoch 430/500
 - 0s - loss: 4.5342e-13
Epoch 431/500
 - 0s - loss: 3.8214e-13
Epoch 432/500
 - 0s - loss: 3.1126e-13
Epoch 433/500
 - 0s - loss: 2.4927e-13
Epoch 434/500
 - 0s - loss: 1.9247e-13
Epoch 435/500
 - 0s - loss: 1.5019e-13
Epoch 436/500
 - 0s - loss: 1.2976e-13
Epoch 437/500
 - 0s - loss: 9.4191e-14
Epoch 438/500
 - 0s - loss: 8.0913e-14
Epoch 439/500
 - 0s - loss: 6.5414e-14
Epoch 440/500
 - 0s - loss: 4.9072e-14
Epoch 441/500
 - 0s - loss: 3.8991e-14
Epoch 442/500
 - 0s - loss: 3.6504e-14
Epoch 443/500
 - 0s - loss: 2.7223e-14
Epoch 444/500
 - 0s - loss: 2.1361e-14
Epoch 445/500
 - 0s - loss: 1.8163e-14
Epoch 446/500
 - 0s - loss: 2.0961e-14
Epoch 447/500
 - 0s - loss: 2.0872e-14
Epoch 448/500
 - 0s - loss: 2.0473e-14
Epoch 449/500
 - 0s - loss: 2.0473e-14
Epoch 450/500
 - 0s - loss: 1.8829e-14
Epoch 451/500
 - 0s - loss: 1.8829e-14
Epoch 452/500
 - 0s - loss: 1.8296e-14


In [13]:
result = model.predict(X, batch_size=n_batch, verbose=0)
for value in result[0,:]:
    print('%.1f' % value)

0.0
0.2
0.4
0.6
0.8


In [18]:
# prepare sequence
length = 5
seq = array([i/float(length) for i in range(length)])
X = seq.reshape(1, length, 1)
y = seq.reshape(1, length, 1)
# define LSTM configuration
n_neurons = length
n_batch = 1
n_epoch = 1000

In [25]:
X

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

In [26]:
y

array([[[0. ],
        [0.2],
        [0.4],
        [0.6],
        [0.8]]])

There are two key points to remember when using the TimeDistributed wrapper layer:
<br>
<br>
The input must be (at least) 3D. This often means that you will need to configure your last LSTM layer prior to your TimeDistributed wrapped Dense layer to return sequences (e.g. set the “return_sequences” argument to “True”).
<br>   
The output will be 3D. This means that if your TimeDistributed wrapped Dense layer is your output layer and you are predicting a sequence, you will need to resize your y array into a 3D vector.


We can define the shape of the output as having 1 sample, 5 time steps, and 1 feature, just like the input sequence, as follows: y = seq.reshape(1, length, 1)
<br><br>
We can define the LSTM hidden layer to return sequences rather than single values by setting the “return_sequences” argument to true.
model.add(LSTM(n_neurons, input_shape=(length, 1), return_sequences=True))
<br><br>
This has the effect of each LSTM unit returning a sequence of 5 outputs, one for each time step in the input data, instead of single output value as in the previous example.

We also can use the TimeDistributed on the output layer to wrap a fully connected Dense layer with a single output.
model.add(TimeDistributed(Dense(1)))
<br><br>
The single output value in the output layer is key. It highlights that we intend to output one time step from the sequence for each time step in the input. It just so happens that we will process 5 time steps of the input sequence at a time.

The TimeDistributed achieves this trick by applying the same Dense layer (same weights) to the LSTMs outputs for one time step at a time. In this way, the output layer only needs one connection to each LSTM unit (plus one bias).

For this reason, the number of training epochs needs to be increased to account for the smaller network capacity. I doubled it from 500 to 1000 to match the first one-to-one example.

In [19]:
# create LSTM
model = Sequential()
model.add(LSTM(n_neurons, input_shape=(length, 1), return_sequences=True))
model.add(TimeDistributed(Dense(1)))
model.compile(loss='mean_squared_error', optimizer='adam')
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_6 (LSTM)                (None, 5, 5)              140       
_________________________________________________________________
time_distributed_2 (TimeDist (None, 5, 1)              6         
Total params: 146
Trainable params: 146
Non-trainable params: 0
_________________________________________________________________
None


In [20]:
# train LSTM
model.fit(X, y, epochs=n_epoch, batch_size=n_batch, verbose=2)

Epoch 1/1000
 - 1s - loss: 0.1063
Epoch 2/1000
 - 0s - loss: 0.1043
Epoch 3/1000
 - 0s - loss: 0.1023
Epoch 4/1000
 - 0s - loss: 0.1004
Epoch 5/1000
 - 0s - loss: 0.0985
Epoch 6/1000
 - 0s - loss: 0.0966
Epoch 7/1000
 - 0s - loss: 0.0947
Epoch 8/1000
 - 0s - loss: 0.0929
Epoch 9/1000
 - 0s - loss: 0.0910
Epoch 10/1000
 - 0s - loss: 0.0892
Epoch 11/1000
 - 0s - loss: 0.0874
Epoch 12/1000
 - 0s - loss: 0.0856
Epoch 13/1000
 - 0s - loss: 0.0839
Epoch 14/1000
 - 0s - loss: 0.0821
Epoch 15/1000
 - 0s - loss: 0.0804
Epoch 16/1000
 - 0s - loss: 0.0787
Epoch 17/1000
 - 0s - loss: 0.0770
Epoch 18/1000
 - 0s - loss: 0.0753
Epoch 19/1000
 - 0s - loss: 0.0737
Epoch 20/1000
 - 0s - loss: 0.0721
Epoch 21/1000
 - 0s - loss: 0.0705
Epoch 22/1000
 - 0s - loss: 0.0689
Epoch 23/1000
 - 0s - loss: 0.0674
Epoch 24/1000
 - 0s - loss: 0.0658
Epoch 25/1000
 - 0s - loss: 0.0643
Epoch 26/1000
 - 0s - loss: 0.0628
Epoch 27/1000
 - 0s - loss: 0.0613
Epoch 28/1000
 - 0s - loss: 0.0599
Epoch 29/1000
 - 0s - loss: 0

Epoch 232/1000
 - 0s - loss: 0.0025
Epoch 233/1000
 - 0s - loss: 0.0025
Epoch 234/1000
 - 0s - loss: 0.0025
Epoch 235/1000
 - 0s - loss: 0.0025
Epoch 236/1000
 - 0s - loss: 0.0024
Epoch 237/1000
 - 0s - loss: 0.0024
Epoch 238/1000
 - 0s - loss: 0.0024
Epoch 239/1000
 - 0s - loss: 0.0024
Epoch 240/1000
 - 0s - loss: 0.0024
Epoch 241/1000
 - 0s - loss: 0.0024
Epoch 242/1000
 - 0s - loss: 0.0024
Epoch 243/1000
 - 0s - loss: 0.0023
Epoch 244/1000
 - 0s - loss: 0.0023
Epoch 245/1000
 - 0s - loss: 0.0023
Epoch 246/1000
 - 0s - loss: 0.0023
Epoch 247/1000
 - 0s - loss: 0.0023
Epoch 248/1000
 - 0s - loss: 0.0023
Epoch 249/1000
 - 0s - loss: 0.0023
Epoch 250/1000
 - 0s - loss: 0.0022
Epoch 251/1000
 - 0s - loss: 0.0022
Epoch 252/1000
 - 0s - loss: 0.0022
Epoch 253/1000
 - 0s - loss: 0.0022
Epoch 254/1000
 - 0s - loss: 0.0022
Epoch 255/1000
 - 0s - loss: 0.0022
Epoch 256/1000
 - 0s - loss: 0.0022
Epoch 257/1000
 - 0s - loss: 0.0022
Epoch 258/1000
 - 0s - loss: 0.0022
Epoch 259/1000
 - 0s - loss:

Epoch 460/1000
 - 0s - loss: 0.0012
Epoch 461/1000
 - 0s - loss: 0.0012
Epoch 462/1000
 - 0s - loss: 0.0012
Epoch 463/1000
 - 0s - loss: 0.0012
Epoch 464/1000
 - 0s - loss: 0.0012
Epoch 465/1000
 - 0s - loss: 0.0012
Epoch 466/1000
 - 0s - loss: 0.0012
Epoch 467/1000
 - 0s - loss: 0.0012
Epoch 468/1000
 - 0s - loss: 0.0011
Epoch 469/1000
 - 0s - loss: 0.0011
Epoch 470/1000
 - 0s - loss: 0.0011
Epoch 471/1000
 - 0s - loss: 0.0011
Epoch 472/1000
 - 0s - loss: 0.0011
Epoch 473/1000
 - 0s - loss: 0.0011
Epoch 474/1000
 - 0s - loss: 0.0011
Epoch 475/1000
 - 0s - loss: 0.0011
Epoch 476/1000
 - 0s - loss: 0.0011
Epoch 477/1000
 - 0s - loss: 0.0011
Epoch 478/1000
 - 0s - loss: 0.0011
Epoch 479/1000
 - 0s - loss: 0.0011
Epoch 480/1000
 - 0s - loss: 0.0011
Epoch 481/1000
 - 0s - loss: 0.0011
Epoch 482/1000
 - 0s - loss: 0.0011
Epoch 483/1000
 - 0s - loss: 0.0011
Epoch 484/1000
 - 0s - loss: 0.0011
Epoch 485/1000
 - 0s - loss: 0.0011
Epoch 486/1000
 - 0s - loss: 0.0011
Epoch 487/1000
 - 0s - loss:

Epoch 674/1000
 - 0s - loss: 7.9059e-04
Epoch 675/1000
 - 0s - loss: 7.8900e-04
Epoch 676/1000
 - 0s - loss: 7.8740e-04
Epoch 677/1000
 - 0s - loss: 7.8581e-04
Epoch 678/1000
 - 0s - loss: 7.8422e-04
Epoch 679/1000
 - 0s - loss: 7.8263e-04
Epoch 680/1000
 - 0s - loss: 7.8104e-04
Epoch 681/1000
 - 0s - loss: 7.7945e-04
Epoch 682/1000
 - 0s - loss: 7.7787e-04
Epoch 683/1000
 - 0s - loss: 7.7628e-04
Epoch 684/1000
 - 0s - loss: 7.7470e-04
Epoch 685/1000
 - 0s - loss: 7.7311e-04
Epoch 686/1000
 - 0s - loss: 7.7153e-04
Epoch 687/1000
 - 0s - loss: 7.6995e-04
Epoch 688/1000
 - 0s - loss: 7.6837e-04
Epoch 689/1000
 - 0s - loss: 7.6679e-04
Epoch 690/1000
 - 0s - loss: 7.6521e-04
Epoch 691/1000
 - 0s - loss: 7.6363e-04
Epoch 692/1000
 - 0s - loss: 7.6206e-04
Epoch 693/1000
 - 0s - loss: 7.6048e-04
Epoch 694/1000
 - 0s - loss: 7.5891e-04
Epoch 695/1000
 - 0s - loss: 7.5734e-04
Epoch 696/1000
 - 0s - loss: 7.5577e-04
Epoch 697/1000
 - 0s - loss: 7.5420e-04
Epoch 698/1000
 - 0s - loss: 7.5263e-04


Epoch 879/1000
 - 0s - loss: 4.8724e-04
Epoch 880/1000
 - 0s - loss: 4.8588e-04
Epoch 881/1000
 - 0s - loss: 4.8453e-04
Epoch 882/1000
 - 0s - loss: 4.8317e-04
Epoch 883/1000
 - 0s - loss: 4.8182e-04
Epoch 884/1000
 - 0s - loss: 4.8046e-04
Epoch 885/1000
 - 0s - loss: 4.7911e-04
Epoch 886/1000
 - 0s - loss: 4.7776e-04
Epoch 887/1000
 - 0s - loss: 4.7641e-04
Epoch 888/1000
 - 0s - loss: 4.7506e-04
Epoch 889/1000
 - 0s - loss: 4.7371e-04
Epoch 890/1000
 - 0s - loss: 4.7237e-04
Epoch 891/1000
 - 0s - loss: 4.7102e-04
Epoch 892/1000
 - 0s - loss: 4.6968e-04
Epoch 893/1000
 - 0s - loss: 4.6834e-04
Epoch 894/1000
 - 0s - loss: 4.6700e-04
Epoch 895/1000
 - 0s - loss: 4.6566e-04
Epoch 896/1000
 - 0s - loss: 4.6432e-04
Epoch 897/1000
 - 0s - loss: 4.6298e-04
Epoch 898/1000
 - 0s - loss: 4.6164e-04
Epoch 899/1000
 - 0s - loss: 4.6031e-04
Epoch 900/1000
 - 0s - loss: 4.5898e-04
Epoch 901/1000
 - 0s - loss: 4.5765e-04
Epoch 902/1000
 - 0s - loss: 4.5632e-04
Epoch 903/1000
 - 0s - loss: 4.5499e-04


In [24]:
# evaluate
result = model.predict(X, batch_size=n_batch, verbose=0)
print(result)
for value in result[0,:,0]:
    print('%.1f' % value)

[[[0.03499379]
  [0.18664536]
  [0.3853772 ]
  [0.59980184]
  [0.8065734 ]]]
0.0
0.2
0.4
0.6
0.8
