What is PyTorch?<br/>
It’s a Python-based scientific computing package targeted at two sets of audiences:
<ul>
    <li>Pytorch Tensors are much much faster than numpy arrays, Hence they are much more used than numpy arrays
    <li> A Tensor is same as an array in numpy, Just that how pytorch makes use of it, makes it faster than numpy
</ul>

In [1]:
import torch

In [2]:
'''An uninitialized matrix is declared,but does not contain definite known values before it is used.When uninitialized 
matrix is created, whatever values were in the allocated memory at the time will appear as the initial values.'''
x = torch.empty(5, 3)  
print(x)

tensor([[0.0000e+00, 0.0000e+00, 1.0599e-35],
        [1.4013e-45, 1.4013e-45, 2.3329e-18],
        [0.0000e+00, 0.0000e+00, 7.0368e+28],
        [3.3127e-18, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [3]:
'''Constructs a randomly initialized matrix, This idea and the idea above will be used to generate data while we will
try to create model and train them on some synthetic data'''
x = torch.rand(5, 3)   
print(x)

tensor([[0.3410, 0.7873, 0.6060],
        [0.4813, 0.5173, 0.4139],
        [0.8591, 0.1049, 0.6021],
        [0.8551, 0.8041, 0.8034],
        [0.5794, 0.5891, 0.4918]])


In [4]:
'''Pretty obvious when you need a matrix of zeros of datatype "long" denoted as dtype you can use torch.zeros'''
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
'''Constructing a tensor from a list is important to know and understand as often you will process and keep data in a 
list which will be easy, but then in order to make operations faster you can change their type to pytorch tensors'''
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
'''Creating a tensor "based on existing tensor" this can come in to be useful when you need mock data based on 
some true data, so that you can create somewhat similar data and train your model on the mock data, by somewhat 
similar data i mean data will be similar in terms of
        a) The shape of tensor
        b) Data-type (float or int or whatever)
There is no gurantee that the data will also follow the distribution that original data is following
'''
x = torch.randn_like(x, dtype=torch.float) 
print(x) 

tensor([ 0.5190, -0.3949])


In [7]:
'''In numpy we have the shape method on arrays, in pytorch we have the size method to get the dimensions of the array'''
x.size()

torch.Size([2])

In [8]:
'''Performing operations on tensors with comments and outputs are as shown below'''
x = torch.tensor([1,2])
y = torch.tensor([2,2])
print('result of addition of x and y:',x+y)
print('result of subtraction of x and y:',x-y)
y = torch.tensor([2])
print('result of addition of x and y where y is broadcasted:',x+y)

result of addition of x and y: tensor([3, 4])
result of subtraction of x and y: tensor([-1,  0])
result of addition of x and y where y is broadcasted: tensor([3, 4])


In [9]:
'''storing outputs in variables can be accomplished in multiple ways'''
result = torch.empty(1,2, dtype = torch.long)
torch.add(x,y, out = result)
result

tensor([3, 4])

There is not just one way to do the addition operation or any other operation on torch, example you can be using the 'add' method in the torch class and then there are multiple other methods, So based on the requirement you can use whatver suits you best.<br><br>
A syntax rule in pytorch: Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.


In [10]:
'''By Default in pytorch inplace=True means that it will modify the input directly, without allocating any additional 
output. It can sometimes slightly decrease the memory usage, but may not always be a valid operation (because the 
original input is destroyed). Here is an example of inplace operation in pytorch'''
x = torch.tensor([1,2])
x.add_(torch.tensor([1]))
x

tensor([2, 3])

In [11]:
'''How can you convert to and fro and use numpy with torch'''
x = torch.rand(5,3,dtype=torch.float)
print(x)
print(x[1:2,:2])   #supports numpy like indexing

tensor([[0.8788, 0.3547, 0.8602],
        [0.1516, 0.5547, 0.8395],
        [0.8102, 0.9294, 0.7232],
        [0.0176, 0.2607, 0.7768],
        [0.9836, 0.4264, 0.4823]])
tensor([[0.1516, 0.5547]])


In [12]:
'''You are already familier with np.reshape the torch equivalent is "view" array.view(shape tuple)'''
x = torch.rand(4,4)
y = x.view(16)
x,y

(tensor([[3.4689e-01, 6.5386e-01, 1.2796e-01, 4.6577e-02],
         [5.2342e-01, 4.9816e-01, 5.3529e-01, 1.3891e-01],
         [7.8292e-01, 2.6357e-01, 1.0029e-01, 3.3866e-01],
         [6.0859e-01, 6.9761e-04, 9.9993e-01, 2.0291e-01]]),
 tensor([3.4689e-01, 6.5386e-01, 1.2796e-01, 4.6577e-02, 5.2342e-01, 4.9816e-01,
         5.3529e-01, 1.3891e-01, 7.8292e-01, 2.6357e-01, 1.0029e-01, 3.3866e-01,
         6.0859e-01, 6.9761e-04, 9.9993e-01, 2.0291e-01]))

In [13]:
z = x.view(2,8)
print('We define actual dimensions in torch:\n',z)
'''The same operation can also be performed as shown below, -1 to torch means that infer the other dimension 
automatically from the shape or size of the parent array'''
z = x.view(-1,8)
print('\n We let torch infer dimensions on its own by giving -1: \n',z)

We define actual dimensions in torch:
 tensor([[3.4689e-01, 6.5386e-01, 1.2796e-01, 4.6577e-02, 5.2342e-01, 4.9816e-01,
         5.3529e-01, 1.3891e-01],
        [7.8292e-01, 2.6357e-01, 1.0029e-01, 3.3866e-01, 6.0859e-01, 6.9761e-04,
         9.9993e-01, 2.0291e-01]])

 We let torch infer dimensions on its own by giving -1: 
 tensor([[3.4689e-01, 6.5386e-01, 1.2796e-01, 4.6577e-02, 5.2342e-01, 4.9816e-01,
         5.3529e-01, 1.3891e-01],
        [7.8292e-01, 2.6357e-01, 1.0029e-01, 3.3866e-01, 6.0859e-01, 6.9761e-04,
         9.9993e-01, 2.0291e-01]])


In [14]:
'''Converting a torch tensor to a numpy and vice-versa'''
a = torch.ones(5)
b = a.numpy()
print(type(a),type(b))
'''Point to notice below is that, The Torch Tensor and NumPy array will share their underlying memory locations 
(if the Torch Tensor is on CPU), and changing one will change the other. Notice operation is only performed
on torch tensor but changes reflect in numpy version as well, this is because they share the same memory'''
a = a.add_(1)
print(a,b)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [15]:
'''We have already seen how to convert a torch tensor to numpy now how to convert a numpy to torch tensor'''
import numpy as np
np_arr = np.ones(5)
b = torch.from_numpy(np_arr)
print(type(b))

<class 'torch.Tensor'>


In [21]:
'''Moving tensors, model or any other object in and out of a device for computations, example: We want the computation 
to be only on cpu, we put all the things on cpu, we want all the computation on gpu we put all on gpu'''
if torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = 'cpu'
'''Here we have said that if cuda is available device=cuda else cpu'''
device

'cpu'

In [22]:
x = torch.rand(3,4)
x.to(device)

tensor([[0.8181, 0.6268, 0.5058, 0.2316],
        [0.8425, 0.8170, 0.6712, 0.8997],
        [0.9012, 0.6415, 0.3288, 0.5498]])

In [23]:
'''Note: If some of the data or model is on cpu and other on gpu, you will not able to communicate among them
you will need everything to be on the same device in order to do any computations on them'''

'Note: If some of the data or model is on cpu and other on gpu, you will not able to communicate among them\nyou will need everything to be on the same device in order to do any computations on them'